global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
  - job_name: 'prometheus_metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: gameplay
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ["host.docker.internal:3001"]
      labels:
        instance: 'Gameplay'

  - job_name: gameplay-lobby
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ["host.docker.internal:3002"]
      labels:
        instance: 'Gameplay-Lobby'

  - job_name: gateway
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ["host.docker.internal:3003"]
      labels:
        instance: 'Gateway'

  - job_name: ws-gateway
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ["host.docker.internal:3004"]
      labels:
        instance: 'WsGateway'

  - job_name: users
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ["host.docker.internal:3005"]
      labels:
        instance: 'Users'

  - job_name: tg
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ["host.docker.internal:3006"]
      labels:
        instance: 'TG'

  - job_name: boost
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ["host.docker.internal:3007"]
      labels:
        instance: 'Boost'

  - job_name: character
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ["host.docker.internal:3008"]
      labels:
        instance: 'Character'

  - job_name: referral
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ["host.docker.internal:3009"]
      labels:
        instance: 'Referral'

  - job_name: collection
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ["host.docker.internal:3010"]
      labels:
        instance: 'Collection'