# global:
#   scrape_interval: 15s
#   scrape_timeout: 10s
#   evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [
        'prometheus:9090',
      ]

  # - job_name: gameplay
  #   honor_timestamps: true
  #   scrape_interval: 15s
  #   scrape_timeout: 10s
  #   metrics_path: /metrics
  #   scheme: http
  #   static_configs:
  #   - targets: ["host.docker.internal:3001"]
  #     labels:
  #       instance: 'Gameplay'

  # - job_name: gameplay-lobby
  #   honor_timestamps: true
  #   scrape_interval: 15s
  #   scrape_timeout: 10s
  #   metrics_path: /metrics
  #   scheme: http
  #   static_configs:
  #   - targets: ["host.docker.internal:3002"]
  #     labels:
  #       instance: 'Gameplay-Lobby'

  - job_name: gateway
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ["gateway:3004"]
      labels:
        instance: 'gateway'

  - job_name: ws-gateway
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ["ws-gateway:3005"]
      labels:
        instance: 'ws-gateway'

  - job_name: users
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ["users:3006"]
      labels:
        instance: 'users'

  # # - job_name: tg
  # #   honor_timestamps: true
  # #   scrape_interval: 15s
  # #   scrape_timeout: 10s
  # #   metrics_path: /metrics
  # #   scheme: http
  # #   static_configs:
  # #   - targets: ["host.docker.internal:3006"]
  # #     labels:
  # #       instance: 'TG'

  - job_name: boosts
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ["boosts:3008"]
      labels:
        instance: 'boosts'

  - job_name: characters
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ["characters:3009"]
      labels:
        instance: 'characters'

  - job_name: game
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ["game:3012"]
      labels:
        instance: 'game'

  # - job_name: referral
  #   honor_timestamps: true
  #   scrape_interval: 15s
  #   scrape_timeout: 10s
  #   metrics_path: /metrics
  #   scheme: http
  #   static_configs:
  #   - targets: ["host.docker.internal:3009"]
  #     labels:
  #       instance: 'Referral'

  # - job_name: collection
  #   honor_timestamps: true
  #   scrape_interval: 15s
  #   scrape_timeout: 10s
  #   metrics_path: /metrics
  #   scheme: http
  #   static_configs:
  #   - targets: ["host.docker.internal:3010"]
  #     labels:
  #       instance: 'Collection'