version: "3"
services:

  gateway:
    build:
        context: .
        dockerfile: seidh.gateway.dockerfile
    container_name: gateway
    ports:
      - "3003:3003"

  ws-gateway:
    build:
        context: .
        dockerfile: seidh.ws-gateway.dockerfile
    container_name: ws-gateway
    ports:
      - "3004:3004"

  # No networks for the rest of services

  gameplay:
    build:
      context: .
      dockerfile: seidh.gameplay.dockerfile
    container_name: gameplay
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "3001:3001"

  gameplay-lobby:
    build:
      context: .
      dockerfile: seidh.gameplay-lobby.dockerfile
    container_name: gameplay-lobby
    ports:
      - "3002:3002"

  users:
    build:
        context: .
        dockerfile: seidh.users.dockerfile
    container_name: users
    depends_on:
      - mongodb
    ports:
      - "3005:3005"

   boost:
    build:
        context: .
        dockerfile: seidh.boost.dockerfile
    container_name: boost
    depends_on:
      - mongodb
    ports:
      - "3007:3007"

  character:
    build:
        context: .
        dockerfile: seidh.character.dockerfile
    container_name: character
    depends_on:
      - mongodb
    ports:
      - "3008:3008"           

  nats:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
  nats-1:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    depends_on: ["nats"]
  nats-2:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    depends_on: ["nats"]

  mongodb:
    image: mongo:4.4.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ferretrec
      - MONGO_INITDB_ROOT_PASSWORD=khlhasdg972^&*TFGy
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

  # node_exporter:
  #   image: quay.io/prometheus/node-exporter:latest
  #   container_name: node_exporter
  #   command:
  #     - '--path.rootfs=/host'
  #   network_mode: host
  #   pid: host
  #   restart: unless-stopped
  #   volumes:
  #     - '/:/host:ro,rslave'    
  #   ports:
  #     - "9100:9100"  

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data_a:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=seidh-admin
      - GF_SECURITY_ADMIN_PASSWORD=ljhsadf972gh*^TYg
    volumes:
      - ./monitoring/grafana:/etc/grafana/provisioning/datasources

volumes:
  mongo_db:
  prometheus_data: