version: "3"
services:

  gateway:
    build:
        context: .
        dockerfile: seidh.gateway.dockerfile
    networks: ["nats"]
    ports:
      - "3003:3003"

  ws-gateway:
    build:
        context: .
        dockerfile: seidh.ws-gateway.dockerfile
    networks: ["nats"]
    ports:
      - "3004:3004"

  gameplay:
    build:
      context: .
      dockerfile: seidh.gameplay.dockerfile
    deploy:
      mode: replicated
      replicas: 1
    networks: ["nats"]

  gameplay-lobby:
    build:
      context: .
      dockerfile: seidh.gameplay-lobby.dockerfile
    networks: ["nats"]  

  nats:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: ["nats"]
  nats-1:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
  nats-2:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]

networks:
  nats:
    name: nats