version: "3"
services:

  gateway:
    build:
        context: .
        dockerfile: seidh.gateway.dockerfile
    ports:
      - "3003:3003"

  ws-gateway:
    build:
        context: .
        dockerfile: seidh.ws-gateway.dockerfile
    ports:
      - "3004:3004"

  users:
    build:
        context: .
        dockerfile: seidh.users.dockerfile
    depends_on:
      - mongodb

  gameplay:
    build:
      context: .
      dockerfile: seidh.gameplay.dockerfile
    deploy:
      mode: replicated
      replicas: 1

  gameplay-lobby:
    build:
      context: .
      dockerfile: seidh.gameplay-lobby.dockerfile

  nats:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
  nats-1:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    depends_on: ["nats"]
  nats-2:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    depends_on: ["nats"]

  mongodb:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db

volumes:
  db:

# mongodb://user:pass@mongodb